# Generated by Django 2.2.10 on 2020-03-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_home', models.URLField()),
                ('desc', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('kategori', models.ManyToManyField(to='mainapp.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('episode_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('episode', models.PositiveSmallIntegerField()),
                ('episode_note', models.TextField()),
                ('episode_title', models.CharField(max_length=80)),
                ('episode_archive', models.URLField(help_text='please use dropbox or anything similar to attach your files, and hook the url to this field')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Course')),
            ],
        ),
    ]
