# Generated by Django 3.1.dev20200306084809 on 2020-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='episode_archive',
            field=models.URLField(help_text='Please use dropbox or anything similar to attach your files, and hook the url to this field'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='episode_title',
            field=models.CharField(max_length=200),
        ),
    ]
