# Generated by Django 3.1.dev20200306084809 on 2020-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200307_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
